# -*- coding: utf-8 -*-
"""Copy of ECEN250-S26-Lab10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gqQwjhZjtC59-hVZbe_2Dgsrcihk5oKt

## You must **train and validate a** machine learning **model on the data generated from Lab 9**.

## You must **display a training and validation loss plot** for your model and you need to **display the accuracy during training**.

##You need to **save your trained model** and successfuly **load your saved model and have it evaluate test data samples**.
(Your trained model needs to be reloaded and make predictions so you can succeed in this lab and use it for future tasks).

## Skeleton code for a DNN and a LSTM are provided below.
You only need to use and show a single model training on the the sequential Lab 9 data. This should be the same model that you save and load and provide the test accuracy for.  

Feel free to add necessary libraries and code cells. If you use the skeleton code cells be aware that they need modifications to work.

(Note: if you press 'ctrl' + '/' when commented out lines are selected, it uncomments them out)

## Framework for a DNN is given below:

## 1. Load data
"""

from google.colab import drive
import numpy as np
import matplotlib.pyplot as plt
drive.mount('/content/drive')
def load_data(filename):
    '''
    General case to load any data from filename
    Output tuple:
        xtr, ytr : Data and labels for training
        xva, yva : Data and labels for validation
        xte, yte : Data and labels for test
    '''
    loaded = np.load(filename)
    xtr = loaded['xtr']
    ytr = loaded['ytr']
    xva = loaded['xva']
    yva = loaded['yva']
    xte = loaded['xte']
    yte = loaded['yte']
    return (xtr, ytr, xva, yva, xte, yte)
xtr, ytr, xva, yva, xte, yte = load_data('/content/drive/MyDrive/new_data.npz')

"""## 2. Define Model"""

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import TensorDataset, DataLoader
import matplotlib.pyplot as plt

#When prompted with “how to fix the machine from getting a stuck accuracy” Claude provided the changes to the nn.Linear (Claude, 2026).
#Claude. (2026). Claude [Large language model]. https://claude.ai/new
model = nn.Sequential(
    nn.Linear(64, 64),
    nn.ReLU(),
    nn.Linear(64, 64),
    nn.ReLU(),
    nn.Linear(64, 64)
)

"""## 3. Select Model Loss Function and Optimizer"""

#When prompted with “how to implement cross entropy” Claude provided graphing code (Claude, 2026).
#Claude. (2026). Claude [Large language model]. https://claude.ai/new
criterion = nn.CrossEntropyLoss()

optimizer = optim.Adam(model.parameters(), lr=0.001)

"""## 4. Train Model"""

import matplotlib.pyplot as plt

#When prompted with “how to graph the data for train_loss, val_loss, train_acc, and val_acc” Gemini provided graphing code (Gemini, 2026).
#Gemini. (2026). Gemini [Large language model]. https://gemini.google.com/app
history = {
    'train_loss': [],
    'val_loss': [],
    'train_acc': [],
    'val_acc': []
}

# #these will need to be changed to correspond to Lab 9 data
X_tensor = torch.tensor(xtr, dtype=torch.float32)
y_tensor = torch.tensor(ytr, dtype=torch.float32)
y_tensor = torch.argmax(y_tensor, dim=-1).long() #code from Claude as cited in previous cell
y_val_tensor = torch.tensor(yva, dtype=torch.float32)
y_val_tensor = torch.argmax(y_val_tensor, dim=-1).long() #code from Claude as cited in previous cell
X_val_tensor = torch.tensor(xva, dtype=torch.float32)
#(handles batching only assumes there to be training data)
dataset = TensorDataset(X_tensor, y_tensor)
loader = DataLoader(dataset, batch_size=10, shuffle=True)
val_dataset = TensorDataset(X_val_tensor, y_val_tensor)
val_loader = DataLoader(val_dataset, batch_size=1, shuffle=True)

# #training loop
epochs = 20 #might want to make that a smaller number

for epoch in range(epochs):
    running_loss = 0.0
    correct = 0
    total = 0
    model.train()
    for batch_X, batch_y in loader:
        #forward pass
        outputs = model(batch_X)
        loss = criterion(outputs, batch_y)

        #backward pass and optimization
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        predicted = torch.argmax(outputs, dim=1) #code from Claude as cited in previous cell

        # Count total samples and correct predictions
        total += batch_y.size(0)
        correct += (predicted == batch_y).sum().item()

        running_loss += loss.item()

    # Calculate epoch metrics
    train_loss = running_loss / len(loader)
    train_acc = correct / total

    v_loss = 0.0
    val_correct = 0
    val_total = 0
    model.eval()
    for batch_X_val, batch_y_val in val_loader:
        #forward pass
        outputs = model(batch_X_val)
        loss = criterion(outputs, batch_y_val)
        predicted = torch.argmax(outputs, dim=1) #code from Claude as cited in previous cell

        # Count total samples and correct predictions
        val_total += batch_y_val.size(0)
        val_correct += (predicted == batch_y_val).sum().item()

        v_loss += loss.item()

    # Calculate epoch metrics
    val_loss = v_loss / len(val_loader)
    val_acc = val_correct / val_total

    #prints training loss (you might want to figure out how to add accuracy and those for validation without leaking data)
    print(f"Epoch [{epoch+1}/{epochs}] Accuracy: {train_acc:.4f}, Epoch_Loss: {train_loss:.4f}")
    print(f"Validation Accuracy: {val_acc:.4f}, Validation_Loss: {val_loss:.4f}")


#This code is provided from the Gemini prompt cited at teh beggining of the cell
    history['train_loss'].append(train_loss)
    history['val_loss'].append(val_loss)
    history['train_acc'].append(train_acc)
    history['val_acc'].append(val_acc)

def plot_metrics(history):
    epochs_range = range(1, len(history['train_loss']) + 1)

    plt.figure(figsize=(12, 5))

    # Plot Loss
    plt.subplot(1, 2, 1)
    plt.plot(epochs_range, history['train_loss'], label='Training Loss', marker='o')
    plt.plot(epochs_range, history['val_loss'], label='Validation Loss', marker='x')
    plt.title('Loss over Epochs')
    plt.xlabel('Epochs')
    plt.ylabel('Loss')
    plt.legend()
    plt.grid(True)

    # Plot Accuracy
    plt.subplot(1, 2, 2)
    plt.plot(epochs_range, history['train_acc'], label='Training Accuracy', marker='o')
    plt.plot(epochs_range, history['val_acc'], label='Validation Accuracy', marker='x')
    plt.title('Accuracy over Epochs')
    plt.xlabel('Epochs')
    plt.ylabel('Accuracy')
    plt.legend()
    plt.grid(True)

    plt.tight_layout()
    plt.show()

# Call the function
plot_metrics(history)

"""Output for 20 epochs

Epoch [1/20] Accuracy: 0.5201, Epoch_Loss: 1.4088
Validation Accuracy: 0.6867, Validation_Loss: 0.8795

Epoch [2/20] Accuracy: 0.7295, Epoch_Loss: 0.7458
Validation Accuracy: 0.7604, Validation_Loss: 0.6544

Epoch [3/20] Accuracy: 0.7942, Epoch_Loss: 0.5689
Validation Accuracy: 0.8082, Validation_Loss: 0.5248

Epoch [4/20] Accuracy: 0.8300, Epoch_Loss: 0.4656
Validation Accuracy: 0.8396, Validation_Loss: 0.4399

Epoch [5/20] Accuracy: 0.8573, Epoch_Loss: 0.3898
Validation Accuracy: 0.8641, Validation_Loss: 0.3727

Epoch [6/20] Accuracy: 0.8776, Epoch_Loss: 0.3336
Validation Accuracy: 0.8834, Validation_Loss: 0.3153

Epoch [7/20] Accuracy: 0.8907, Epoch_Loss: 0.2951
Validation Accuracy: 0.8899, Validation_Loss: 0.2984

Epoch [8/20] Accuracy: 0.8998, Epoch_Loss: 0.2689
Validation Accuracy: 0.8924, Validation_Loss: 0.2883

Epoch [9/20] Accuracy: 0.9067, Epoch_Loss: 0.2488
Validation Accuracy: 0.8978, Validation_Loss: 0.2823

Epoch [10/20] Accuracy: 0.9121, Epoch_Loss: 0.2334
Validation Accuracy: 0.9135, Validation_Loss: 0.2296

Epoch [11/20] Accuracy: 0.9173, Epoch_Loss: 0.2185
Validation Accuracy: 0.9101, Validation_Loss: 0.2463

Epoch [12/20] Accuracy: 0.9221, Epoch_Loss: 0.2052
Validation Accuracy: 0.9217, Validation_Loss: 0.2076

Epoch [13/20] Accuracy: 0.9267, Epoch_Loss: 0.1926
Validation Accuracy: 0.9204, Validation_Loss: 0.2154

Epoch [14/20] Accuracy: 0.9310, Epoch_Loss: 0.1815
Validation Accuracy: 0.9275, Validation_Loss: 0.1978

Epoch [15/20] Accuracy: 0.9333, Epoch_Loss: 0.1723
Validation Accuracy: 0.9320, Validation_Loss: 0.1810

Epoch [16/20] Accuracy: 0.9371, Epoch_Loss: 0.1641
Validation Accuracy: 0.9358, Validation_Loss: 0.1685

Epoch [17/20] Accuracy: 0.9389, Epoch_Loss: 0.1586
Validation Accuracy: 0.9382, Validation_Loss: 0.1672

Epoch [18/20] Accuracy: 0.9407, Epoch_Loss: 0.1520
Validation Accuracy: 0.9364, Validation_Loss: 0.1684

Epoch [19/20] Accuracy: 0.9427, Epoch_Loss: 0.1474
Validation Accuracy: 0.9404, Validation_Loss: 0.1599

Epoch [20/20] Accuracy: 0.9446, Epoch_Loss: 0.1431
Validation Accuracy: 0.9417, Validation_Loss: 0.1521

## 5. Evaluate Model
"""

model.eval()  # evaluation mode
with torch.no_grad():  # no gradient tracking
    outputs = model(X_tensor)

    preds = torch.argmax(outputs, dim=1)
    correct = (preds == y_tensor).sum().item()
    accuracy = correct / y_tensor.size(0)

print('Accuracy: %.2f' % (accuracy * 100))

"""## 6. Retrieve Predictions"""

model.eval()
X_test_tensor = torch.tensor(xte, dtype=torch.float32)
with torch.no_grad():
    predictions = model(X_test_tensor)
print(predictions)

"""## Practice Waveform Conversion"""

!pip install pydub
!pip install SpeechRecognition
from pydub import AudioSegment
import matplotlib.pyplot as plt
from scipy.io import wavfile
from tempfile import mktemp
mp3_audio = AudioSegment.from_file('/content/drive/MyDrive/Morse Code Sample 1 - 10 WPM Audio.mp3', format="mp3") # read mp3
wname = mktemp('.wav') # use temporary file
mp3_audio.export(wname, format="wav") # convert to wav
FS, data = wavfile.read(wname) # read wav file
# import required modules
from os import path
from pydub import AudioSegment
# assign files
input_file = "/content/drive/MyDrive/Morse Code Sample 1 - 10 WPM Audio.mp3"
output_file = "/content/drive/MyDrive/result.wav"
# convert mp3 file to wav file
sound = AudioSegment.from_mp3(input_file)
sound.export(output_file, format="wav")

"""## Waveform

"""

from pydub import AudioSegment
import matplotlib.pyplot as plt
from scipy.io import wavfile
from tempfile import mktemp
mp3_audio = AudioSegment.from_file('/content/drive/MyDrive/Morse Code Sample 1 - 10 WPM Audio.mp3', format="mp3") # read mp3
wname = mktemp('.wav') # use temporary file
mp3_audio.export(wname, format="wav") # convert to wav
FS, data = wavfile.read(wname) # read wav file
n_data = data / 32768.0
time = int(FS*0.01)

#Gemini
rms_amplitudes = []
for i in range(0, len(n_data), time):
    window = n_data[i : i + time]
    if len(window) > 0:
        rms = np.sqrt(np.mean(window**2))
        rms_amplitudes.append(rms)

# 3. Thresholding to create a binary string
threshold = 0.05  # Adjust based on your audio noise floor
binary_str = "".join(['1' if a > threshold else '0' for a in rms_amplitudes])

# 4. Split by zeros to find beep lengths
# Filter out empty strings caused by multiple consecutive zeros
beeps = [len(group) for group in binary_str.split('0') if group]

for length in beeps:
    if 10 <= length <= 20: # Allowing a buffer around 15
        print('dit')
    elif 40 <= length <= 50: # Allowing a buffer around 45
        print('dah')

for x in beeps:
  if (x == 'dit')
    random_int = np.random.randint(1,3)
    for i in random_int
      value = np.random.randint(12, 4/3) #normal distribution
      beep.append(value)
  elif (x == 'dah')
    random_int = np.random.randint(4,9)
    for i in range(random_int)
      value = np.random.randint(12, 4/3) #normal distribution
      beep.append(value)
  random_int = np.random.randint(1,3)
  for i in random_int
    beep.append(0)

"""## New Section

## Framework for LSTM is given below:

## 1. Importing necessary modules.
"""

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

"""## 2. Importing And Preprocessing MNIST Data"""

(X_train, y_train),(X_test, y_test) = mnist.load_data()  # unpacks images to x_train/x_test and labels to y_train/y_test
X_train = X_train.astype('float32') / 255.0
X_test = X_test.astype('float32') / 255.0

"""## 3. Creating An LSTM Network"""

class LSTMClassifier(nn.Module):
    def __init__(self, input_size, hidden_size=128, num_classes=10):
        super(LSTMClassifier, self).__init__()

        self.lstm1 = nn.LSTM(input_size=input_size, hidden_size=hidden_size, batch_first=True)
        self.dropout1 = nn.Dropout(0.2)

        self.lstm2 = nn.LSTM(input_size=hidden_size, hidden_size=hidden_size, batch_first=True)

        self.fc1 = nn.Linear(hidden_size, 64)
        self.dropout2 = nn.Dropout(0.2)
        self.fc2 = nn.Linear(64, num_classes)

    def forward(self, x):
        # x shape: (batch_size, seq_len, input_size)

        out, _ = self.lstm1(x)              # return_sequences=True
        out = self.dropout1(out)

        out, _ = self.lstm2(out)           # return_sequences=False (we'll take last output)
        out = out[:, -1, :]                # last timestep

        out = F.relu(self.fc1(out))
        out = self.dropout2(out)
        out = self.fc2(out)

        return out#F.softmax(out, dim=1)

"""## 4. Compiling The LSTM Network And Selecting The Loss Function And Optimizer"""

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

model = LSTMClassifier(input_size=X_train.shape[2]).to(device)

criterion = nn.CrossEntropyLoss()  # equivalent to sparse_categorical_crossentropy
optimizer = optim.Adam(model.parameters(), lr=0.001, weight_decay=1e-6)

"""## 5. Training and Validating The LSTM Model"""

epochs = 3
batch_size = 32

# Convert to tensors
X_train_tensor = torch.tensor(X_train, dtype=torch.float32).to(device)
y_train_tensor = torch.tensor(y_train, dtype=torch.long).to(device)

X_test_tensor = torch.tensor(X_test, dtype=torch.float32).to(device)
y_test_tensor = torch.tensor(y_test, dtype=torch.long).to(device)

# Simple batching
train_dataset = torch.utils.data.TensorDataset(X_train_tensor, y_train_tensor)
train_loader = torch.utils.data.DataLoader(train_dataset, batch_size=batch_size, shuffle=True)

test_dataset = torch.utils.data.TensorDataset(X_test_tensor, y_test_tensor)
test_loader = torch.utils.data.DataLoader(test_dataset, batch_size=batch_size)

for epoch in range(epochs):
    model.train()
    train_loss = 0
    correct = 0
    total = 0

    for X_batch, y_batch in train_loader:
        optimizer.zero_grad()

        outputs = model(X_batch)
        loss = criterion(outputs, y_batch)

        loss.backward()
        optimizer.step()

        train_loss += loss.item()
        _, predicted = torch.max(outputs, 1)
        total += y_batch.size(0)
        correct += (predicted == y_batch).sum().item()

    train_acc = correct / total

    # Validation
    model.eval()
    val_loss = 0
    correct = 0
    total = 0

    with torch.no_grad():
        for X_batch, y_batch in test_loader:
            outputs = model(X_batch)
            loss = criterion(outputs, y_batch)

            val_loss += loss.item()
            _, predicted = torch.max(outputs, 1)
            total += y_batch.size(0)
            correct += (predicted == y_batch).sum().item()

    val_acc = correct / total

    print(f"Epoch [{epoch+1}/{epochs}] "
          f"Train Loss: {train_loss:.4f}, Train Acc: {train_acc:.4f} | "
          f"Val Loss: {val_loss:.4f}, Val Acc: {val_acc:.4f}")

"""## 6. Saving And Loading The Model"""

torch.save(model.state_dict(), "lstm_model.pth")

model = LSTMClassifier(input_size=X_test.shape[2])
model.load_state_dict(torch.load("lstm_model.pth"))
model.to(device)
model.eval()

"""## 7. Checking The Accuracy On Test Set"""

model.eval()

test_loss = 0
correct = 0
total = 0

with torch.no_grad():
    for X_batch, y_batch in test_loader:
        X_batch = X_batch.to(device)
        y_batch = y_batch.to(device)

        outputs = model(X_batch)
        loss = criterion(outputs, y_batch)

        test_loss += loss.item()

        _, predicted = torch.max(outputs, 1)
        total += y_batch.size(0)
        correct += (predicted == y_batch).sum().item()

test_acc = correct / total

print('Test Loss: {}'.format(test_loss))
print('Test Accuracy: {}'.format(test_acc))



"""# Extra

This is not required for your submission, this contains additional code that can help you try to map the model's predictions to the actual characters they represent.
"""

# Codebook = np.load('/content/drive/whereeveryouputit/Codebook.npy', allow_pickle=True).item()#note, it is the original .npy file, NOT the .npz file you used to training

# list(Codebook.keys())

# for i in range(len(theListOfCodebook.Keys,what,youThoughtIwouldDoItAllForYou?)):
#   print(i, " : ", themorescode[i])