# -*- coding: utf-8 -*-
"""ECEN250-S26-Lab11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B_vkcBXUtTBZ54utOVIPo0WB9xxM8N_i
"""

!pip install pydub
!pip install SpeechRecognition
from pydub import AudioSegment
from os import path
import matplotlib.pyplot as plt
from scipy.io import wavfile
from tempfile import mktemp
from google.colab import drive
from pydub import AudioSegment
import matplotlib.pyplot as plt
from scipy.io import wavfile
from tempfile import mktemp
import numpy as np
import random
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import TensorDataset, DataLoader
from google.colab import drive

def load_model(PATH):
  model = nn.Sequential(
    nn.Linear(64, 64),
    nn.ReLU(),
    nn.Linear(64, 64),
    nn.ReLU(),
    nn.Linear(64, 64)
  )
  model.load_state_dict(torch.load(PATH))
  return model

def file_to_input(file):
  mp3_audio = AudioSegment.from_file(file, format="mp3") # read mp3
  wname = mktemp('.wav') # use temporary file
  mp3_audio.export(wname, format="wav") # convert to wav
  FS, data = wavfile.read(wname) # read wav file
  # assign files
  input_file = file
  # convert mp3 file to wav file
  sound = AudioSegment.from_mp3(input_file)
  sound.export(wname, format="wav")

  #Normalize
  normalized = data/32768.0

  #RMS Amplitudes
  rms_amps = []
  samples_per_period = int(FS*0.01)
  for i in range(0, len(normalized), samples_per_period):
    samples = normalized[i:i+samples_per_period]
    rms = np.sqrt(np.mean(samples**2))
    rms_amps.append(rms)

  #Set Threshold, Convert to Binary
  binary_string = ""
  for i in rms_amps:
    if i > (0.5*np.max(rms_amps)):
      binary_string += "1"
    else:
      binary_string += "0"
  #Split by 0s
  beeps = binary_string.split("0")
  #Identify Lengths
  morse_code = []
  space = 0
  for i in beeps:
    if len(i) == 0:
      space += 1
    else:
      if space > 20:
        morse_code.append("end char")
      space = 0
    if len(i) >= 6 and len(i) <= 15:
      morse_code.append("dit")
    if len(i) >= 20 and len(i) <= 45:
      morse_code.append("dah")
  if beeps[-1] != "end char":
    morse_code.append("end char")
  if morse_code[0] == "end char":
    morse_code.pop(0)
  morse_sub = []
  morse_code_f = []
  for i in morse_code:
    if i == "end char":
      morse_code_f.append(morse_sub)
      morse_sub = []
    else:
      morse_sub.append(i)

  #Convert to input

  input_data = []
  final_input = []

  for mcode in morse_code_f:
    for x in mcode:
      if (x == 'dit'):
        random_int = random.randint(1,3)
        for i in range(random_int):
          value = random.gauss(12, 4/3)
          input_data.append(value/16)
      if (x == 'dah'):
        random_int = random.randint(4,9)
        for i in range(random_int):
          value = random.gauss(12, 4/3)
          input_data.append(value/16)
      random_int = random.randint(1,3)
      for i in range(random_int):
        input_data.append(0)
    zeros = 64 - len(input_data)
    for i in range(zeros):
      input_data.append(0)
    final_input.append(input_data)
    input_data = []
  return final_input

def convert_to_text(input,model):
  Codebook = np.load(f'{main_folder}/Codebook.npy',allow_pickle=True).item()
  model.eval()
  string = ""
  X_tensor = torch.tensor(input, dtype=torch.float32)
  with torch.no_grad():
      output = model(X_tensor)
      preds = torch.argmax(output, dim=1)
  for i in preds:
    string += list(Codebook.keys())[i]
  return string

#Load Model
main_folder = "/content/drive/MyDrive/"
model = load_model(f'{main_folder}/Morse_Code_DNN.pt')

input1 = file_to_input('/content/drive/MyDrive/Morse Code Sample 1 - 10 WPM Audio.mp3')
preds1 = convert_to_text(input1,model)
print("Below is the output of the model as a string")
print(preds1)

from google.colab import drive
drive.mount('/content/drive')
NOTEBOOK_PATH = "/content/drive/MyDrive/ECEN250-S26-Lab11.ipynb" # Enter here, the path to your notebook file, e.g. "/content/drive/MyDriveECEN250-S26-Lab5.ipynb". Do not change the lines below, and make sure you do not have multiple notebooks with the same path.
! pip install playwright
! jupyter nbconvert --to webpdf --allow-chromium-download "$NOTEBOOK_PATH"